package com.techgel.StaticData;

import com.techgel.common.entity.adminSettings.AttractTalent;
import com.techgel.common.entity.adminSettings.News;

import java.util.List;

public abstract class AttractTalentData {
    public static List<AttractTalent> get() {
        return List.of(
                new AttractTalent(1L, "Thu hút nhân tài", "Attract talents", "/imgs/hr/boost-handshake.webp",
                "<p class=\"text-center\">Việc tuyển chọn đội ngũ nhân sự chất lượng, đáp ứng yêu cầu công việc góp phần thực hiện mục tiêu và định hướng phát triển Công ty là mục tiêu hàng đầu trong hoạt động nhân sự: <br /> <br /> Quy trình tuyển dụng được thực hiện một cách bài bản, đảm bảo tính minh bạch, thống nhất; cùng với hệ thống tiêu chí tuyển dụng khoa học và có tính thực chiến cao nhằm lựa chọn ra những ứng viên phù hợp cả về năng lực chuyên môn, kỹ năng, thái độ. Bên cạnh đó, công tác xây dựng thương hiệu tuyển dụng thông qua việc ký kết hợp tác chiến lược với các trường đại học uy tín trong nước cũng được Công ty đặt ưu tiên hàng đầu. Bằng việc triển khai các chương trình thực tập, trao học bổng, tổ chức các buổi hội thảo chuyên đề,… Tất cả những yếu tố trên cùng góp phần giúp TECHGEL tìm kiếm và chọn ra những ứng viên đầu vào chất lượng, phù hợp với tiêu chí tuyển dụng, định hướng phát triển của Công ty và văn hóa doanh nghiệp./p>",
                "<p class=\"text-center\"> The recruitment of high-quality personnel who meet job requirements is a top priority in TECHGEL’s human resources strategy, contributing to the achievement of the Company’s goals and development orientation. <br /><br /> The recruitment process is carried out in a professional manner, ensuring transparency and consistency. It is supported by a set of scientific and highly practical criteria to select candidates who are a good fit in terms of professional competence, skills, and attitude. <br /><br /> In addition, TECHGEL places high importance on building its employer brand by establishing strategic partnerships with reputable universities across the country. Through internship programs, scholarship grants, and specialized seminars, the Company proactively connects with young talent. <br /><br /> All these efforts work together to help TECHGEL identify and recruit high-quality candidates who align with the Company’s recruitment criteria, development orientation, and corporate culture. </p>",
                "<p></p><div style=\"text-align: center;\" bis_skin_checked=\"1\"><span style=\"color: rgb(20, 36, 90); font-family: Roboto, sans-serif; font-size: 20px; font-weight: 700;\">Tại Techgel, con người là trung tâm của mọi chiến lược</span></div><span style=\"color: rgb(20, 36, 90); font-family: Roboto, sans-serif; font-size: 20px; font-weight: 700; text-align: center;\"><div style=\"text-align: right\" bis_skin_checked=\"1\">Chúng tôi xây dựng chính sách lương thưởng minh bạch, cạnh tranh, kết hợp thưởng dự án, thưởng hiệu suất và thưởng thành tích cuối năm</div></span><i style=\"margin: 0px; padding: 0px; font-family: Roboto, sans-serif; color: rgb(20, 36, 90); font-size: 20px; font-weight: 700; text-align: center;\"><div style=\"\" bis_skin_checked=\"1\"><i style=\"margin: 0px; padding: 0px;\">Môi trường làm việc năng động, bền vững – cùng bạn phát triển!</i></div></i><p></p>",
                "<p></p> <div style=\"text-align: center;\" bis_skin_checked=\"1\"> <span style=\"color: rgb(20, 36, 90); font-family: Roboto, sans-serif; font-size: 20px; font-weight: 700;\"> At Techgel, people are at the heart of every strategy </span> </div> <div style=\"\" bis_skin_checked=\"1\"> <span style=\"color: rgb(20, 36, 90); font-family: Roboto, sans-serif; font-size: 20px; font-weight: 700;\"> We build transparent and competitive compensation policies, combining project bonuses, performance incentives, and year-end rewards. </span> </div> <div style=\"\" bis_skin_checked=\"1\"> <i style=\"color: rgb(20, 36, 90); font-family: Roboto, sans-serif; font-size: 20px; font-weight: 700;\"> A dynamic and sustainable working environment – growing with you! </i> </div> <p></p>")
        );
    }
}
