package com.techgel.StaticData;

import com.techgel.common.entity.adminSettings.CareerRecruitment;
import com.techgel.common.entity.adminSettings.News;
import com.techgel.common.entity.enums.NewsType;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.List;

public abstract class CareerRecruitmentData {
    public static List<CareerRecruitment> get() {
        return List.of(
                new CareerRecruitment(1L, "Nhân viên kiểm soát chi phí", "Cost Control Officer",
                        1, "Thỏa thuận thuận theo năng lực", "Negotiable Based on Qualifications and Experience",
                        "Tốt nghiệp Đại học/Cao đẳng chuyên ngành Kế toán, Tài chính, Kinh tế Xây dựng.", "",
                        "Có ít nhất 2 năm kinh nghiệm trong vị trí kiểm soát chi phí, ưu tiên trong ngành xây dựng M&E.",
                        "At least 2 years of experience in a cost control position, preferably in the M&E construction industry.",
                        "30 Phan Chu Trinh, phường 02, quận Bình Thạnh, Thành phố Hồ Chí Minh.", "30 Phan Chu Trinh, Ward 02, Binh Thanh District, Ho Chi Minh City.",
                        new Date(),
                        "<p style= font-size: medium;\"><b>Quyền lợi:</b></p><p style= font-size: medium; margin-left: 1.5625rem;\">- Môi trường làm việc:</p><p style= font-size: medium; margin-left: 3.125rem;\">+ Cơ hội làm việc trong môi trường trẻ - năng động – thân thiện, chuyên nghiệp, hệ thống quy trình tác nghiệp rõ ràng, nhiều cơ hội thăng tiến theo năng lực.</p><p style= font-size: medium; margin-left: 3.125rem;\">+ Làm việc hoàn toàn dân chủ với những ý kiến đóng góp được trao đổi trực tiếp với ban lãnh đạo công ty.</p><p style= font-size: medium; margin-left: 1.5625rem;\">- Chế độ:</p><p style= font-size: medium; margin-left: 3.125rem;\">+ Lễ tết, Hiếu hỉ, sinh nhật, ốm đau, thai sản,…</p><p style= font-size: medium; margin-left: 3.125rem;\">+ Được hưởng đầy đủ quyền lợi theo quy định của Luật lao động: BHXH, BHYT,BHTN</p><p style=font-size: medium; margin-left: 3.125rem;\">+ Giờ làm việc : Theo giờ hành chính từ Thứ 2 – Sáng Thứ Bảy.</p><p style= font-size: medium;\"><b>Nội dung công việc:</b></p><p style= font-size: medium; margin-left: 1.5625rem;\">- Theo dõi và kiểm soát chi phí của các dự án M&amp;E, đảm bảo tuân thủ ngân sách đã duyệt.</p><p style= font-size: medium; margin-left: 1.5625rem;\">- Kiểm tra và xác minh tính hợp lệ của các hồ sơ thanh toán, hợp đồng với nhà thầu phụ, nhà cung cấp.</p><p style=font-size: medium; margin-left: 1.5625rem;\">- Phân tích, đánh giá các yếu tố tác động đến chi phí dự án, đề xuất phương án tối ưu hóa chi phí.</p><p style= font-size: medium; margin-left: 1.5625rem;\">- Theo dõi dòng tiền, công nợ phải trả, tiến độ thanh toán cho nhà cung cấp và thầu phụ.</p><p style= font-size: medium; margin-left: 1.5625rem;\">- Lập báo cáo chi phí định kỳ, so sánh chi phí thực tế với kế hoạch để cảnh báo rủi ro.</p><p style= font-size: medium; margin-left: 1.5625rem;\">- Phối hợp với phòng kế toán, phòng đấu thầu để kiểm tra và rà soát đơn giá, khối lượng nghiệm thu.</p><p style=\"font-size: medium; margin-left: 1.5625rem;\"> <br><div style=\"text-align: center;\" bis_skin_checked=\"1\"><span style=\"color: var(--black);\">Liên hệ : Email: </span><u style=\"\"><font color=\"#9c00ff\">thuy.ntt@techgel.com</font></u><span style=\"color: var(--black);\"> SĐT/Zalo: </span><font color=\"#ff0000\">0963 205 687</font></div></p>",
                        "<p style=\"font-size: medium;\"><b>Benefits:</b></p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- <b>Working Environment:</b></p> <p style=\"font-size: medium; margin-left: 3.125rem;\">+ Opportunity to work in a young, dynamic, friendly, and professional environment with clear operational procedures and great opportunities for advancement based on performance.</p> <p style=\"font-size: medium; margin-left: 3.125rem;\">+ A democratic workplace where all feedback and suggestions can be directly discussed with the company’s leadership.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- <b>Employee Benefits:</b></p> <p style=\"font-size: medium; margin-left: 3.125rem;\">+ Holiday, wedding, funeral, birthday, sick leave, maternity, and other allowances.</p> <p style=\"font-size: medium; margin-left: 3.125rem;\">+ Full entitlements as per Vietnamese Labor Law: Social Insurance, Health Insurance, and Unemployment Insurance.</p> <p style=\"font-size: medium; margin-left: 3.125rem;\">+ Working hours: Office hours from Monday to Saturday morning.</p> <p style=\"font-size: medium;\"><b>Job Description:</b></p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Monitor and control costs of M&E projects, ensuring adherence to approved budgets.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Check and verify the validity of payment documents and contracts with subcontractors and suppliers.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Analyze and assess factors affecting project costs, and propose cost optimization solutions.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Track cash flow, accounts payable, and payment schedules for suppliers and subcontractors.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Prepare periodic cost reports, compare actual costs with planned budgets, and issue early warnings for potential risks.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Coordinate with the accounting and bidding departments to review and verify unit prices and acceptance quantities.</p> <p style=\"text-align: center; font-size: medium;\">Contact: Email: <u><font color=\"#9c00ff\">thuy.ntt@techgel.com</font></u> | Phone/Zalo: <font color=\"#ff0000\">0963 205 687</font></p>",
                        "/imgs/hr/career_avatar.png"),
                new CareerRecruitment(2L, "Kế toán Dự án", "Project Accountant",
                        1, "Thỏa thuận thuận theo năng lực", "Negotiable Based on Qualifications and Experience",
                        "Tốt nghiệp Đại học/Cao đẳng chuyên ngành Kế toán, Tài chính, Kiểm toán.", "Graduated from University/College with a major in Accounting, Finance, or Auditing.",
                        "Kinh nghiệm từ 2-3 năm trong lĩnh vực kế toán xây dựng, ưu tiên ứng viên có kinh nghiệm trong ngành M&E.",
                        "2–3 years of experience in construction accounting, preferably with experience in the M&E (Mechanical & Electrical) industry.",
                        "30 Phan Chu Trinh, phường 02, quận Bình Thạnh, Thành phố Hồ Chí Minh.", "30 Phan Chu Trinh, Ward 02, Binh Thanh District, Ho Chi Minh City.",
                        new Date(),
                        "<p style= font-size: medium;\"><b>Quyền lợi:</b></p><p style= font-size: medium; margin-left: 1.5625rem;\">- Môi trường làm việc:</p><p style= font-size: medium; margin-left: 3.125rem;\">+ Cơ hội làm việc trong môi trường trẻ - năng động – thân thiện, chuyên nghiệp, hệ thống quy trình tác nghiệp rõ ràng, nhiều cơ hội thăng tiến theo năng lực.</p><p style= font-size: medium; margin-left: 3.125rem;\">+ Làm việc hoàn toàn dân chủ với những ý kiến đóng góp được trao đổi trực tiếp với ban lãnh đạo công ty.</p><p style= font-size: medium; margin-left: 1.5625rem;\">- Chế độ:</p><p style= font-size: medium; margin-left: 3.125rem;\">+ Lễ tết, Hiếu hỉ, sinh nhật, ốm đau, thai sản,…</p><p style= font-size: medium; margin-left: 3.125rem;\">+ Được hưởng đầy đủ quyền lợi theo quy định của Luật lao động: BHXH, BHYT,BHTN</p><p style=font-size: medium; margin-left: 3.125rem;\">+ Giờ làm việc : Theo giờ hành chính từ Thứ 2 – Sáng Thứ Bảy.</p><p style= font-size: medium;\"><b>Nội dung công việc:</b></p><p style= font-size: medium; margin-left: 1.5625rem;\">- Theo dõi và kiểm soát chi phí của các dự án M&amp;E, đảm bảo tuân thủ ngân sách đã duyệt.</p><p style= font-size: medium; margin-left: 1.5625rem;\">- Kiểm tra và xác minh tính hợp lệ của các hồ sơ thanh toán, hợp đồng với nhà thầu phụ, nhà cung cấp.</p><p style=font-size: medium; margin-left: 1.5625rem;\">- Phân tích, đánh giá các yếu tố tác động đến chi phí dự án, đề xuất phương án tối ưu hóa chi phí.</p><p style= font-size: medium; margin-left: 1.5625rem;\">- Theo dõi dòng tiền, công nợ phải trả, tiến độ thanh toán cho nhà cung cấp và thầu phụ.</p><p style= font-size: medium; margin-left: 1.5625rem;\">- Lập báo cáo chi phí định kỳ, so sánh chi phí thực tế với kế hoạch để cảnh báo rủi ro.</p><p style= font-size: medium; margin-left: 1.5625rem;\">- Phối hợp với phòng kế toán, phòng đấu thầu để kiểm tra và rà soát đơn giá, khối lượng nghiệm thu.</p><p style=\"font-size: medium; margin-left: 1.5625rem;\"> <br><div style=\"text-align: center;\" bis_skin_checked=\"1\"><span style=\"color: var(--black);\">Liên hệ : Email: </span><u style=\"\"><font color=\"#9c00ff\">thuy.ntt@techgel.com</font></u><span style=\"color: var(--black);\"> SĐT/Zalo: </span><font color=\"#ff0000\">0963 205 687</font></div></p>",
                        "<p style=\"font-size: medium;\"><b>Benefits:</b></p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- <b>Working environment:</b></p> <p style=\"font-size: medium; margin-left: 3.125rem;\">+ Opportunity to work in a young, dynamic, friendly, and professional environment with a clearly defined workflow and many opportunities for advancement based on capability.</p> <p style=\"font-size: medium; margin-left: 3.125rem;\">+ Democratic workplace where employees can share their ideas directly with the company's leadership.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- <b>Welfare policies:</b></p> <p style=\"font-size: medium; margin-left: 3.125rem;\">+ Holidays, weddings, funerals, birthdays, sick leave, maternity leave, etc.</p> <p style=\"font-size: medium; margin-left: 3.125rem;\">+ Full entitlement to labor law benefits: Social Insurance, Health Insurance, and Unemployment Insurance.</p> <p style=\"font-size: medium; margin-left: 3.125rem;\">+ Working hours: Office hours from Monday to Saturday morning.</p> <p style=\"font-size: medium;\"><b>Job Description:</b></p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Monitor and control costs for M&E projects, ensuring compliance with approved budgets.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Review and verify the validity of payment documents, contracts with subcontractors, and suppliers.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Analyze and evaluate factors affecting project costs; propose cost optimization solutions.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Track cash flow, accounts payable, and payment schedules to suppliers and subcontractors.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Prepare periodic cost reports; compare actual costs with budget plans to flag potential risks.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\">- Coordinate with the accounting and bidding departments to review and verify unit prices and accepted quantities.</p> <p style=\"font-size: medium; margin-left: 1.5625rem;\"><br> <div style=\"text-align: center;\"> <span style=\"color: var(--black);\">Contact: Email: </span> <u><font color=\"#9c00ff\">thuy.ntt@techgel.com</font></u> <span style=\"color: var(--black);\"> Phone/Zalo: </span> <font color=\"#ff0000\">0963 205 687</font> </div></p>",
                        "/imgs/hr/career_avatar.png"));
    }
}
