package com.techgel.StaticData;

import com.techgel.common.entity.adminSettings.WhatWeDoOurBusinessLine;
import com.techgel.common.entity.adminSettings.WhatWeDoService;
import com.techgel.common.entity.adminSettings.WhatWeDoServiceItems;

import java.util.List;

public abstract class WhatWeDoOurBusinessLineData {
        public static List<WhatWeDoOurBusinessLine> get() {
                return List.of(
                        new WhatWeDoOurBusinessLine(1L, "Lĩnh vực hoạt động", "Our business lines",
                                "<p><img src=\"/imgs/business-line/safety-handshake.jpg\" style=\"width: 50%; float: right;\" class=\"note-float-right\"></p><h3 class=\"fs-30 fw-bold business-line header\" style=\"font-family: Roboto, sans-serif; line-height: 1.2; color: rgb(20, 36, 90); margin: 0px 0px 1rem; padding: 0px; font-weight: 700 !important; font-size: 34px !important;\">Tổng Thầu</h3><p class=\"business-line paragraph\" style=\"margin-bottom: 0.25rem; color: rgb(0, 0, 0); padding: 0px; font-family: Roboto, sans-serif; font-size: 16px;\">TECHGEL hoạt động trong lĩnh vực nghiên cứu, ứng dụng và chuyển giao các giải pháp kỹ thuật – công nghệ nhằm hỗ trợ tiến trình hiện đại hoá và phát triển bền vững tại Việt Nam. Chúng tôi tập trung triển khai toàn diện các dự án từ khâu khảo sát, thiết kế, triển khai công nghệ đến vận hành và đào tạo, đặc biệt trong các lĩnh vực công nghiệp, xây dựng, năng lượng và hạ tầng kỹ thuật.</p><p class=\"business-line paragraph\" style=\"margin-bottom: 0.25rem; color: rgb(0, 0, 0); padding: 0px; font-family: Roboto, sans-serif; font-size: 16px;\">Với năng lực tích hợp đa ngành, hệ thống quản trị bài bản, đội ngũ kỹ sư và chuyên gia giàu kinh nghiệm, cùng sự chủ động trong việc làm chủ công nghệ, TECHGEL cam kết mang đến cho khách hàng và đối tác:</p><ul class=\"business-line list\" style=\"margin: 1rem 0px 0px; color: rgb(0, 0, 0); padding: 0px 0px 0px 16px; font-family: Roboto, sans-serif; font-size: 16px;\"><li style=\"margin: 0.625rem 0px; padding: 0px; font-size: 1rem; line-height: 1.75; list-style: square; font-weight: bold;\">Các giải pháp tối ưu, phù hợp với thực tiễn.</li><li style=\"margin: 0.625rem 0px; padding: 0px; font-size: 1rem; line-height: 1.75; list-style: square; font-weight: bold;\">Đảm bảo tiến độ và chất lượng triển khai.</li><li style=\"margin: 0.625rem 0px; padding: 0px; font-size: 1rem; line-height: 1.75; list-style: square; font-weight: bold;\">Giảm thiểu chi phí đầu tư mà vẫn đảm bảo hiệu quả vận hành.</li></ul><div class=\"business-line-quality-icon icon\" bis_skin_checked=\"1\" style=\"margin: 0px; padding: 0px; font-family: Roboto, sans-serif; display: flex; flex-direction: column; text-align: center; width: fit-content; color: rgb(0, 0, 0); font-size: 16px;\"><div class=\"business-line-quality-icon icon\" bis_skin_checked=\"1\" style=\"margin-top: 0px; margin-right: 0px; margin-bottom: 0px; padding: 0px; display: flex; flex-direction: column; width: fit-content;\"><div class=\"business-line-quality-icon icon\" bis_skin_checked=\"1\" style=\"margin: 0px; padding: 0px; display: flex; flex-direction: column; width: fit-content; background-color: rgb(233, 233, 233);\"><br></div></div></div><div bis_skin_checked=\"1\"><br></div>",
                                "<p><img src=\"/imgs/business-line/safety-handshake.jpg\" style=\"float: right; width: 50%;\" class=\"note-float-right\"></p><h3 class=\"fs-30 fw-bold business-line header\" style=\"font-family: Roboto, sans-serif; line-height: 1.2; color: rgb(20, 36, 90); margin: 0px 0px 1rem; padding: 0px; font-weight: 700 !important; font-size: 34px !important;\">General Contractor</h3><p data-start=\"0\" data-end=\"411\"><span data-start=\"0\" data-end=\"411\">TECHGEL operates in the field of research, application, and transfer of technical and technological solutions to support the modernization process and sustainable development in Vietnam. We focus on the comprehensive implementation of projects—from survey, design, and technology deployment to operation and training—especially in the sectors of industry, construction, energy, and technical infrastructure.</span></p><p class=\"business-line paragraph\" style=\"margin-bottom: 0.25rem; color: rgb(0, 0, 0); padding: 0px; font-family: Roboto, sans-serif; font-size: 16px;\">\n" +
                                        "</p><p data-start=\"413\" data-end=\"644\" data-is-last-node=\"\" data-is-only-node=\"\"><span data-start=\"413\" data-end=\"644\" data-is-last-node=\"\">With multi-disciplinary integration capabilities, a systematic management system, a team of experienced engineers and experts, and proactive technological mastery, TECHGEL is committed to delivering to our clients and partners:</span></p><ul class=\"business-line list\" style=\"margin: 1rem 0px 0px; color: rgb(0, 0, 0); padding: 0px 0px 0px 16px; font-family: Roboto, sans-serif; font-size: 16px;\"><li style=\"margin: 0.625rem 0px; padding: 0px; font-size: 1rem; line-height: 1.75; list-style: square; font-weight: bold;\">Optimal solutions tailored to practical needs.</li><li style=\"margin: 0.625rem 0px; padding: 0px; font-size: 1rem; line-height: 1.75; list-style: square; font-weight: bold;\">Guaranteed project timelines and implementation quality.</li><li style=\"margin: 0.625rem 0px; padding: 0px; font-size: 1rem; line-height: 1.75; list-style: square; font-weight: bold;\">Minimized investment costs while ensuring operational efficiency.</li></ul><div class=\"business-line-quality-icon icon\" bis_skin_checked=\"1\" style=\"margin: 0px; padding: 0px; font-family: Roboto, sans-serif; display: flex; flex-direction: column; text-align: center; width: fit-content; color: rgb(0, 0, 0); font-size: 16px;\"><div class=\"business-line-quality-icon icon\" bis_skin_checked=\"1\" style=\"margin-top: 0px; margin-right: 0px; margin-bottom: 0px; padding: 0px; display: flex; flex-direction: column; width: fit-content;\"><div class=\"business-line-quality-icon icon\" bis_skin_checked=\"1\" style=\"margin: 0px; padding: 0px; display: flex; flex-direction: column; width: fit-content; background-color: rgb(233, 233, 233);\"><br></div></div></div><div bis_skin_checked=\"1\"><br></div>",
                                "/imgs/banners/tech-field.jpg")
                );
        }
}
