package com.techgel.StaticData;

import com.techgel.common.entity.adminSettings.WhatWeDoService;
import com.techgel.common.entity.adminSettings.WhatWeDoServiceItems;
import com.techgel.common.entity.adminSettings.WhatWeDoSustainableDevelopment;

import java.util.List;

public abstract class WhatWeDoSustainableDevelopmentData {
        public static List<WhatWeDoSustainableDevelopment> get() {
                return List.of(
                        new WhatWeDoSustainableDevelopment(1L,
                                "Phát triển bền vững", "Sustainable Development",
                                "/imgs/banners/growth-sustain.png",
                                "<h2 class=\"pb-3\" style=\"margin: 0px 0px 0.5rem; padding-top: 0px; padding-right: 0px; padding-left: 0px; font-family: Roboto, sans-serif; line-height: 1; font-size: 20px; color: rgb(54, 66, 80); text-align: center; padding-bottom: 1rem !important;\">KINH DOANH BỀN VỮNG THIẾT LẬP NỀN TẢNG CHO CỘNG ĐỒNG THỊNH VƯỢNG</h2><h3 style=\"margin: 0px 0px 0.5rem; padding: 0px; font-family: Roboto, sans-serif; line-height: 1.2; color: rgb(0, 0, 0); text-align: center; font-size: 34px !important;\">Từ kế hoạch trên giấy đến hành động thực tiễn.</h3><h3 style=\"margin: 0px 0px 0.5rem; padding: 0px; font-family: Roboto, sans-serif; line-height: 1.2; color: rgb(0, 0, 0); text-align: center; font-size: 34px !important;\">Từ ý niệm ban đầu đến tính cam kết dài lâu.</h3><h3 style=\"margin: 0px 0px 0.5rem; padding: 0px; font-family: Roboto, sans-serif; line-height: 1.2; color: rgb(0, 0, 0); text-align: center; font-size: 34px !important;\">Đó là cách chúng tôi nói, hiểu và làm</h3><h3 style=\"margin: 0px 0px 0.5rem; padding: 0px; font-family: Roboto, sans-serif; line-height: 1.2; color: rgb(0, 0, 0); text-align: center; font-size: 34px !important;\">về&nbsp;<i style=\"margin: 0px; padding: 0px;\">PHÁT TRIỂN BỀN VỮNG.</i></h3>",
                                "<h2 class=\"pb-3\" style=\"margin: 0px 0px 0.5rem; padding-top: 0px; padding-right: 0px; padding-left: 0px; font-family: Roboto, sans-serif; line-height: 1; font-size: 20px; color: rgb(54, 66, 80); text-align: center; padding-bottom: 1rem !important;\">SUSTAINABLE BUSINESS – ESTABLISHING THE FOUNDATION FOR A PROSPEROUS COMMUNITY</h2><h3 style=\"margin: 0px 0px 0.5rem; padding: 0px; font-family: Roboto, sans-serif; line-height: 1.2; color: rgb(0, 0, 0); text-align: center; font-size: 34px !important;\">From plans on paper to actions in reality.</h3><h3 style=\"margin: 0px 0px 0.5rem; padding: 0px; font-family: Roboto, sans-serif; line-height: 1.2; color: rgb(0, 0, 0); text-align: center; font-size: 34px !important;\">From initial ideas to long-term commitment.</h3><h3 style=\"margin: 0px 0px 0.5rem; padding: 0px; font-family: Roboto, sans-serif; line-height: 1.2; color: rgb(0, 0, 0); text-align: center; font-size: 34px !important;\">That’s how we speak, understand, and act</h3><h3 style=\"margin: 0px 0px 0.5rem; padding: 0px; font-family: Roboto, sans-serif; line-height: 1.2; color: rgb(0, 0, 0); text-align: center; font-size: 34px !important;\"><i style=\"margin: 0px; padding: 0px;\">when it comes to <strong data-start=\"151\" data-end=\"178\">SUSTAINABLE DEVELOPMENT</strong>.</i></h3>",
                                "Cam kết phát triển bền vững", "Commitment to Sustainable Development",
                                "<h1 class=\"title text-center split-collab text-white\" style=\"margin-top: 0px; margin-bottom: 0.5rem; padding: 0px; font-family: Roboto, sans-serif; line-height: 1.2; opacity: 1; font-size: 64px !important; color: rgb(255, 255, 255) !important;\"></h1><h2 class=\"pb-3\" style=\"margin: 0px 0px 0.5rem; padding-top: 0px; padding-right: 0px; padding-left: 0px; font-family: Roboto, sans-serif; line-height: 1; font-size: 20px; color: rgb(54, 66, 80); text-align: center; padding-bottom: 1rem !important;\"><div data-sal-delay=\"200\" data-sal=\"zoom-in\" data-sal-duration=\"800\" bis_skin_checked=\"1\" class=\"sal-animate\" style=\"margin: 0px; padding: 0px; transition-duration: 0.8s; transition-delay: 0.2s; transition-timing-function: ease; opacity: 1; transition-property: opacity, transform; transform: none; color: rgb(0, 0, 0); font-size: 16px; text-align: start;\"><p class=\"text-white\" style=\"margin-bottom: 1rem; padding: 0px; text-align: center; color: rgb(255, 255, 255) !important;\">Thế giới ngày càng phụ thuộc vào các Công ty đưa ra các lựa chọn phát triển bền vững.</p><p class=\"text-white\" style=\"margin-bottom: 1rem; padding: 0px; text-align: center; color: rgb(255, 255, 255) !important;\">Techgel nhận thức được trách nhiệm đúng đắn sứ mệnh cộng giá trị cho các bên liên quan – khách hàng, đối tác, môi trường, cộng đồng, quốc gia, và toàn cầu nói chung cũng như sự phát triển của mỗi con người trong tổ chức nói riêng.</p></div></h2>",
                                "<h1 class=\"title text-center split-collab text-white\" style=\"margin-top: 0px; margin-bottom: 0.5rem; padding: 0px; font-family: Roboto, sans-serif; line-height: 1.2; opacity: 1; font-size: 64px !important; color: rgb(255, 255, 255) !important;\"></h1><h2 class=\"pb-3\" style=\"margin: 0px 0px 0.5rem; padding-top: 0px; padding-right: 0px; padding-left: 0px; font-family: Roboto, sans-serif; line-height: 1; font-size: 20px; text-align: center; padding-bottom: 1rem !important;\"><div data-sal-delay=\"200\" data-sal=\"zoom-in\" data-sal-duration=\"800\" bis_skin_checked=\"1\" class=\"sal-animate\" style=\"margin: 0px; padding: 0px; transition-duration: 0.8s; transition-delay: 0.2s; transition-timing-function: ease; opacity: 1; transition-property: opacity, transform; transform: none; font-size: 16px; text-align: start;\"><p class=\"text-white\" style=\"margin-bottom: 1rem; padding: 0px; text-align: center;\"><font color=\"#ffffff\">As the world increasingly relies on companies to make sustainable choices,</font></p><p class=\"text-white\" style=\"margin-bottom: 1rem; padding: 0px; text-align: center;\"><font color=\"#ffffff\"><strong data-start=\"122\" data-end=\"133\" style=\"text-align: start;\">Techgel</strong><span style=\"text-align: start;\"> recognizes its rightful responsibility and mission to create shared value for all stakeholders — customers, partners, the environment, the community, the nation, and the world at large — as well as to foster the development of every individual within the organization.</span></font></p></div></h2>")
                );
        }
}
